Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -1,30 +1,61 @@
-name: Django CI
+name: ciTest
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["dev"]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 4
-      matrix:
-        python-version: [3.7, 3.8, 3.9]
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
       with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install Dependencies
+        python-version: '3.12'
+
+    - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-    - name: Run Tests
+    - name: Lint code
+      id: lint
       run: |
-        python manage.py test
+        pip install flake8
+        flake8 . > flake8_errors.txt || true
+    - name: Notify Slack about Linting Errors
+      if: failure() # Notify only if linting fails
+      run: |
+        lint_errors=$(cat flake8_errors.txt || echo "No linting errors")
+        curl -X POST -H 'Content-type: application/json' \
+        --data "{\"text\":\"Linting completed with errors: \n${lint_errors}\"}" \
+        ${{ secrets.SLACK_WEBHOOK_URL }}
+    - name: Run tests
+      id: test
+      run: |
+        pip install pytest
+        pytest > pytest_output.txt || true
+    - name: Notify Slack about Testing Errors
+      if: failure() # Notify only if testing fails
+      run: |
+        test_errors=$(cat pytest_output.txt || echo "No test errors")
+        curl -X POST -H 'Content-type: application/json' \
+        --data "{\"text\":\"Testing completed with errors: \n${test_errors}\"}" \
+        ${{ secrets.SLACK_WEBHOOK_URL }}
+    - name: Login to Docker Hub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+    - name: Build and push Docker image
+      uses: docker/build-push-action@v4
+      with:
+        context: .
+        push: true
+        tags: sarra247/repopixi:pixiii
